### ISSUE TITLE
won't build on MacOS 11.3.1 with current node (from Homebrew)

### ISSUE THREAD

**Issue by laogujimbob** [Steccas/ProtonClient#6]
Building on MacOS Big Sur 11.3.1.  Sorry - this error listing is beyond my capabilities. 

```
./build.sh --mac
Building for Mac

Preparing Electron app...

Converting icons...

Packaging... This will take a few seconds, maybe minutes if the requested Electron isn't cached yet...
Packaging app for platform darwin x64 using electron v11.3.0
Error: Cannot find module '/Users/fred/Downloads/ProtonClient/node_modules/xmldom/lib/dom-parser.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:349:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:562:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:27)
    at Function.Module._load (node:internal/modules/cjs/loader:774:27)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/fred/Downloads/ProtonClient/node_modules/plist/lib/parse.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/fred/Downloads/ProtonClient/node_modules/plist/index.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/fred/Downloads/ProtonClient/node_modules/xmldom/package.json',
  requestPath: 'xmldom'
}
```

**Comment by Steccas** [comment]
Hi, try to remove package.json

Anyways I don't really know about macs to be honest.

Did you install the prerequisites as stated in [Nativefier documentation](https://www.npmjs.com/package/nativefier)?

**Comment by laogujimbob** [comment]
Thanks for replying.

I am using nativefier 43.1.3 and node 16.2.0, both of which are installed using homebrew and are as up to date as possible

I removed node_modules/xmldom/package.json but now it fails with `Error: Cannot find module 'xmldom'`
Clearly I don't know how to fix this and randomly deleting package.json files is not the answer!

Thanks for your efforts - I'll try to pull down a new set of files from github and re-run `./build.sh --mac` every so often, but it looks like my ProtonClient days might be numbered!!

**Comment by Steccas** [comment]
Try to delete package.json in the root folder if present. I meant that.

In any case, there is a built version in the releases version.

**Comment by Steccas** [comment]
Since there is no answer I'm closing

**Comment by macbugs** [comment]
**Same issue here:**

```
% ./build.sh --mac
Building for Mac
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'nativefier'
Require stack:
- /Users/admin/BUILD/ProtonClient/proton_client_mac.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/admin/BUILD/ProtonClient/proton_client_mac.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/admin/BUILD/ProtonClient/proton_client_mac.js' ]
}

Node.js v17.7.1
```
...but Nativefier is in my $PATH...
```
% nativefier --version       
46.1.1
```

**Comment by Unundra** [comment]
I had the same error while using a global install of Nativefier, solved it by installing Nativefier again to the current directory.

It built fine but there's an "invalid character" error at login due to an [Electron bug](https://github.com/electron/electron/issues/31018).
